//! AUTO-GENERATED by scripts/reverse-engineer-nouveau.py — do not hand-edit.
//! Nouveau MODULE_FIRMWARE and nvkm_gsp_fwif tables, clean-room constants.

#![allow(dead_code)]

extern crate alloc;

/// Firmware bundle style declared by Nouveau GSP chip files.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NouveauFirmwareStyle {
    /// booter_load + booter_unload + bootloader + gsp
    Booter,
    /// fmc + bootloader + gsp (Hopper/Blackwell path)
    Fmc,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct NouveauFirmwareNeed {
    pub chip: &'static str,
    pub version: &'static str,
    pub style: NouveauFirmwareStyle,
}

/// Every `NVKM_GSP_FIRMWARE_BOOTER(chip, vers)` declaration.
pub const NOUVEAU_BOOTER_FIRMWARE: &[NouveauFirmwareNeed] = &[
    NouveauFirmwareNeed {
        chip: "ad102",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad102",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad103",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad103",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad104",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad104",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad106",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad106",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad107",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ad107",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga100",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga100",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga102",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga102",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga103",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga103",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga104",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga104",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga106",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga106",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga107",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "ga107",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu102",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu102",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu104",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu104",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu106",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu106",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu116",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu116",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu117",
        version: "535.113.01",
        style: NouveauFirmwareStyle::Booter,
    },
    NouveauFirmwareNeed {
        chip: "tu117",
        version: "570.144",
        style: NouveauFirmwareStyle::Booter,
    },
];

/// Every `NVKM_GSP_FIRMWARE_FMC(chip, vers)` declaration.
pub const NOUVEAU_FMC_FIRMWARE: &[NouveauFirmwareNeed] = &[
    NouveauFirmwareNeed {
        chip: "gb100",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
    NouveauFirmwareNeed {
        chip: "gb102",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
    NouveauFirmwareNeed {
        chip: "gb202",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
    NouveauFirmwareNeed {
        chip: "gb203",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
    NouveauFirmwareNeed {
        chip: "gb205",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
    NouveauFirmwareNeed {
        chip: "gb206",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
    NouveauFirmwareNeed {
        chip: "gb207",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
    NouveauFirmwareNeed {
        chip: "gh100",
        version: "570.144",
        style: NouveauFirmwareStyle::Fmc,
    },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct NouveauFwifEntry {
    pub chip_file: &'static str,
    pub priority: i32,
    pub load_fn: &'static str,
    pub version: &'static str,
    pub rm_impl: &'static str,
}

/// Parsed `nvkm_gsp_fwif` table rows (priority, load, RM version).
pub const NOUVEAU_GSP_FWIF: &[NouveauFwifEntry] = &[
    NouveauFwifEntry {
        chip_file: "ad102",
        priority: 1,
        load_fn: "tu102_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_ga102",
    },
    NouveauFwifEntry {
        chip_file: "ad102",
        priority: 0,
        load_fn: "tu102_gsp_load",
        version: "535.113.01",
        rm_impl: "r535_rm_ga102",
    },
    NouveauFwifEntry {
        chip_file: "ga100",
        priority: 1,
        load_fn: "tu102_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_tu102",
    },
    NouveauFwifEntry {
        chip_file: "ga100",
        priority: 0,
        load_fn: "tu102_gsp_load",
        version: "535.113.01",
        rm_impl: "r535_rm_tu102",
    },
    NouveauFwifEntry {
        chip_file: "ga102",
        priority: 1,
        load_fn: "tu102_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_ga102",
    },
    NouveauFwifEntry {
        chip_file: "ga102",
        priority: 0,
        load_fn: "tu102_gsp_load",
        version: "535.113.01",
        rm_impl: "r535_rm_ga102",
    },
    NouveauFwifEntry {
        chip_file: "gb100",
        priority: 0,
        load_fn: "gh100_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_gb10x",
    },
    NouveauFwifEntry {
        chip_file: "gb202",
        priority: 0,
        load_fn: "gh100_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_gb20x",
    },
    NouveauFwifEntry {
        chip_file: "gh100",
        priority: 0,
        load_fn: "gh100_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_gh100",
    },
    NouveauFwifEntry {
        chip_file: "tu102",
        priority: 1,
        load_fn: "tu102_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_tu102",
    },
    NouveauFwifEntry {
        chip_file: "tu102",
        priority: 0,
        load_fn: "tu102_gsp_load",
        version: "535.113.01",
        rm_impl: "r535_rm_tu102",
    },
    NouveauFwifEntry {
        chip_file: "tu116",
        priority: 1,
        load_fn: "tu102_gsp_load",
        version: "570.144",
        rm_impl: "r570_rm_tu102",
    },
    NouveauFwifEntry {
        chip_file: "tu116",
        priority: 0,
        load_fn: "tu102_gsp_load",
        version: "535.113.01",
        rm_impl: "r535_rm_tu102",
    },
];

/// ELF `.fwsignature_*` section preferred by chip file.
pub const NOUVEAU_SIG_SECTIONS: &[(&str, &str)] = &[
    ("ad102", ".fwsignature_ad10x"),
    ("ga100", ".fwsignature_ga100"),
    ("ga102", ".fwsignature_ga10x"),
    ("gb100", ".fwsignature_gb10x"),
    ("gb202", ".fwsignature_gb20x"),
    ("gh100", ".fwsignature_gh100"),
    ("tu102", ".fwsignature_tu10x"),
    ("tu116", ".fwsignature_tu11x"),
];

/// Relative linux-firmware path for a booter-style role.
pub fn booter_path(chip: &str, version: &str, role: &str) -> alloc::string::String {
    use alloc::string::String;
    let mut s = String::new();
    s.push_str("nvidia/");
    s.push_str(chip);
    s.push_str("/gsp/");
    s.push_str(role);
    s.push('-');
    s.push_str(version);
    s.push_str(".bin");
    s
}

pub fn required_roles(style: NouveauFirmwareStyle) -> &'static [&'static str] {
    match style {
        NouveauFirmwareStyle::Booter => &["booter_load", "booter_unload", "bootloader", "gsp"],
        NouveauFirmwareStyle::Fmc => &["fmc", "bootloader", "gsp"],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn tables_nonempty_and_turing_present() {
        assert!(!NOUVEAU_BOOTER_FIRMWARE.is_empty());
        assert!(!NOUVEAU_GSP_FWIF.is_empty());
        assert!(NOUVEAU_BOOTER_FIRMWARE.iter().any(|e| e.chip == "tu102"));
        assert!(NOUVEAU_FMC_FIRMWARE
            .iter()
            .any(|e| e.chip.starts_with("gb")));
    }
}
