//! Nouveau-shaped GSP load plan + Hermes evidence-driven session.
//!
//! Load order reverse-engineered from `tu102_gsp_load` / `gh100_gsp_load`:
//! Booter path: gsp RM + bootloader + booter_load + booter_unload
//! FMC path:    fmc + bootloader + gsp RM

use alloc::vec::Vec;

use hermes_core::{
    chaos::{ChaosScheduler, ChaosSnapshot},
    HermesManifold, HermesPhase, ManifoldFault,
};
use hermes_gsp::{run_bringup, BringupRequest, HardwareEvidence, NvidiaGspFirmwareAuthority};

use crate::chip::{chip_hint_from_device_id, NouveauChip};
use crate::firmware_manifest::{
    booter_path, required_roles, NouveauFirmwareStyle, NOUVEAU_BOOTER_FIRMWARE,
    NOUVEAU_FMC_FIRMWARE, NOUVEAU_GSP_FWIF,
};
use crate::nvkm::{NvkmDevice, NvkmError, SubdevPhase};

/// Phase of the Nouveau GSP subdevice (Hermes-extended).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
#[repr(u8)]
pub enum GspPhase {
    Absent = 0,
    FwListed = 1,
    FwLoaded = 2,
    Booted = 3,
    RmRunning = 4,
    /// Hermes-only: Online certificate sealed (stricter than Nouveau `running`).
    HermesOnline = 5,
    Failed = 6,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GspLoadPlan {
    pub chip: NouveauChip,
    pub version: &'static str,
    pub style: NouveauFirmwareStyle,
    pub roles: &'static [&'static str],
    pub paths: Vec<&'static str>,
    pub rm_impl: &'static str,
    pub sig_section: Option<&'static str>,
}

/// Build the firmware load plan Nouveau would request for a chip + preferred version.
pub fn plan_gsp_load(chip: NouveauChip, prefer_version: &str) -> Result<GspLoadPlan, NvkmError> {
    let canon = chip.firmware_canonical();
    let style = if canon.uses_fmc() {
        NouveauFirmwareStyle::Fmc
    } else {
        NouveauFirmwareStyle::Booter
    };

    let table = match style {
        NouveauFirmwareStyle::Booter => NOUVEAU_BOOTER_FIRMWARE,
        NouveauFirmwareStyle::Fmc => NOUVEAU_FMC_FIRMWARE,
    };

    // Firmware may be declared on alias chips (e.g. tu104) while canonical is tu102.
    let entry = table
        .iter()
        .find(|e| e.chip == canon.as_str() && e.version == prefer_version)
        .or_else(|| {
            table
                .iter()
                .find(|e| e.chip == chip.as_str() && e.version == prefer_version)
        })
        .or_else(|| table.iter().find(|e| e.chip == canon.as_str()))
        .or_else(|| table.iter().find(|e| e.chip == chip.as_str()))
        .ok_or(NvkmError::UnsupportedChip)?;

    let roles = required_roles(style);
    // Store path templates as static strings built into firmware_manifest helpers
    // via leaked const paths for roles — we recompute in tests with booter_path.
    let mut paths = Vec::new();
    for role in roles {
        // Keep role list; concrete paths generated by `path_for`.
        let _ = role;
        paths.push(*role);
    }

    let chip_key = canon.as_str();
    let fwif = NOUVEAU_GSP_FWIF.iter().find(|e| {
        e.version == entry.version
            && (e.chip_file == chip_key
                || e.chip_file.starts_with(&chip_key[..chip_key.len().min(4)]))
    });

    let rm_impl = fwif.map(|e| e.rm_impl).unwrap_or("unknown");
    let sig_section = crate::firmware_manifest::NOUVEAU_SIG_SECTIONS
        .iter()
        .find(|(c, _)| *c == chip_key || *c == chip.as_str())
        .map(|(_, s)| *s);

    Ok(GspLoadPlan {
        chip: canon,
        version: entry.version,
        style,
        roles,
        paths,
        rm_impl,
        sig_section,
    })
}

impl GspLoadPlan {
    pub fn linux_firmware_path(&self, role: &str) -> alloc::string::String {
        booter_path(self.chip.as_str(), self.version, role)
    }
}

/// Session state combining Nouveau load plan with Hermes manifold.
#[derive(Clone, Debug)]
pub struct GspSession {
    pub device: NvkmDevice,
    pub plan: GspLoadPlan,
    pub phase: GspPhase,
    pub subdev: SubdevPhase,
    pub manifold: HermesManifold,
    pub nouveau_running: bool,
    /// Shared nonlinear service state for firmware/session turns.
    chaos: ChaosScheduler,
    chaos_service_quantum_us: u32,
}

impl GspSession {
    pub fn open(device: NvkmDevice, prefer_version: &str) -> Result<Self, NvkmError> {
        if !device.cfg_nv_gsp_rm {
            return Err(NvkmError::GspDisabled);
        }
        let chip = NouveauChip::from_str_name(device.chip_name)
            .or_else(|| chip_hint_from_device_id(device.identity.device_id))
            .ok_or(NvkmError::UnsupportedChip)?;
        let plan = plan_gsp_load(chip, prefer_version)?;
        Ok(Self {
            device,
            plan,
            phase: GspPhase::FwListed,
            subdev: SubdevPhase::Constructed,
            manifold: HermesManifold::dark(1),
            nouveau_running: false,
            chaos: ChaosScheduler::new(),
            chaos_service_quantum_us: 1,
        })
    }

    fn service_turn(&mut self) {
        self.chaos_service_quantum_us = self.chaos.next_interval(0.01);
    }

    /// Current bounded host-side service interval used by the GSP session.
    pub fn service_quantum_us(&self) -> u32 {
        self.chaos_service_quantum_us
    }

    /// Expose attractor state for diagnostics without affecting firmware bytes
    /// or the evidence required for an Online certificate.
    pub fn chaos_snapshot(&self) -> ChaosSnapshot {
        self.chaos.snapshot()
    }

    /// Nouveau-style "running" without Hermes Online certificate.
    pub fn mark_nouveau_running(&mut self) {
        self.service_turn();
        self.nouveau_running = true;
        self.phase = GspPhase::RmRunning;
        self.subdev = SubdevPhase::Running;
    }

    /// Hermes superior path: only Online after shared bring-up evidence.
    pub fn hermes_online_from_bringup(
        &mut self,
        gsp_rm_image: &[u8],
        authority: NvidiaGspFirmwareAuthority<'_>,
        hardware: HardwareEvidence,
        platform: &impl hermes_core::HermesPlatform,
    ) -> Result<(), ManifoldFault> {
        self.service_turn();
        let mut req = BringupRequest::with_defaults(self.device.identity, gsp_rm_image, authority);
        req.hardware = hardware;
        let report = run_bringup(platform, &req);
        self.manifold = report.manifold;
        if report.is_online() {
            self.phase = GspPhase::HermesOnline;
            self.nouveau_running = true;
            self.subdev = SubdevPhase::Running;
            Ok(())
        } else {
            self.phase = GspPhase::Failed;
            // Map missing evidence to manifold fault if present
            match report.fault {
                Some(hermes_gsp::BringupFault::Manifold(m)) => Err(m),
                _ => Err(ManifoldFault::MissingFirmware),
            }
        }
    }

    pub fn is_hermes_online(&self) -> bool {
        self.phase == GspPhase::HermesOnline && self.manifold.is_online()
    }

    /// Nouveau can report running while Hermes still refuses Online — that is intentional.
    pub fn nouveau_running_without_hermes_online(&self) -> bool {
        self.nouveau_running && self.manifold.phase != HermesPhase::Online
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hermes_core::{pci_identity, NVIDIA_VENDOR_ID};
    use hermes_gsp::{firmware_version, sha256_bytes, FirmwareFamily, NvidiaGspFirmwareManifest};
    use hermes_linux::SimPlatform;

    #[test]
    fn tu102_plan_lists_booter_roles() {
        let plan = plan_gsp_load(NouveauChip::Tu102, "570.144").unwrap();
        assert_eq!(plan.style, NouveauFirmwareStyle::Booter);
        assert!(plan.roles.contains(&"booter_load"));
        assert!(plan.roles.contains(&"gsp"));
        let p = plan.linux_firmware_path("gsp");
        assert_eq!(p, "nvidia/tu102/gsp/gsp-570.144.bin");
    }

    #[test]
    fn gb202_plan_uses_fmc() {
        let plan = plan_gsp_load(NouveauChip::Gb202, "570.144").unwrap();
        assert_eq!(plan.style, NouveauFirmwareStyle::Fmc);
        assert!(plan.roles.contains(&"fmc"));
    }

    #[test]
    fn hermes_online_stricter_than_nouveau_running() {
        let id = pci_identity(NVIDIA_VENDOR_ID, 0x1fb9, 0x03, 0x00);
        let dev = NvkmDevice::new(id, "tu102");
        let mut session = GspSession::open(dev, "570.144").unwrap();
        session.mark_nouveau_running();
        assert!((1..=50).contains(&session.service_quantum_us()));
        assert!(session.chaos_snapshot().lyapunov_exponent.is_finite());
        assert!(session.nouveau_running_without_hermes_online());
        assert!(!session.is_hermes_online());

        let payload = b"nouveau-hermes-superiority";
        let digest = sha256_bytes(payload);
        let manifest = NvidiaGspFirmwareManifest::new(
            FirmwareFamily::Tu10x,
            firmware_version(1, 0, 0),
            payload.len() as u32,
            digest,
        );
        let auth = NvidiaGspFirmwareAuthority::new(core::slice::from_ref(&manifest));
        let plat = SimPlatform::new();
        session
            .hermes_online_from_bringup(payload, auth, HardwareEvidence::full(), &plat)
            .unwrap();
        assert!(session.is_hermes_online());
        assert!(!session.nouveau_running_without_hermes_online());
    }
}
