//! AUTO-GENERATED by scripts/reverse-engineer-cccl.py — CCCL CUB modules.
//! CCCL version pin: 3.5.0

#![allow(dead_code)]

extern crate alloc;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CubModule {
    pub layer: &'static str,
    pub name: &'static str,
}

pub const CUB_MODULES: &[CubModule] = &[
    CubModule { layer: "agent", name: "agent_adjacent_difference" },
    CubModule { layer: "agent", name: "agent_batch_memcpy" },
    CubModule { layer: "agent", name: "agent_batched_topk" },
    CubModule { layer: "agent", name: "agent_find" },
    CubModule { layer: "agent", name: "agent_find_bound_sorted_values" },
    CubModule { layer: "agent", name: "agent_for" },
    CubModule { layer: "agent", name: "agent_histogram" },
    CubModule { layer: "agent", name: "agent_merge" },
    CubModule { layer: "agent", name: "agent_merge_sort" },
    CubModule { layer: "agent", name: "agent_radix_sort_downsweep" },
    CubModule { layer: "agent", name: "agent_radix_sort_histogram" },
    CubModule { layer: "agent", name: "agent_radix_sort_onesweep" },
    CubModule { layer: "agent", name: "agent_radix_sort_upsweep" },
    CubModule { layer: "agent", name: "agent_reduce" },
    CubModule { layer: "agent", name: "agent_reduce_by_key" },
    CubModule { layer: "agent", name: "agent_rle" },
    CubModule { layer: "agent", name: "agent_scan" },
    CubModule { layer: "agent", name: "agent_scan_by_key" },
    CubModule { layer: "agent", name: "agent_segmented_radix_sort" },
    CubModule { layer: "agent", name: "agent_select_if" },
    CubModule { layer: "agent", name: "agent_sub_warp_merge_sort" },
    CubModule { layer: "agent", name: "agent_three_way_partition" },
    CubModule { layer: "agent", name: "agent_topk" },
    CubModule { layer: "agent", name: "agent_unique_by_key" },
    CubModule { layer: "agent", name: "single_pass_scan_operators" },
    CubModule { layer: "block", name: "block_adjacent_difference" },
    CubModule { layer: "block", name: "block_discontinuity" },
    CubModule { layer: "block", name: "block_exchange" },
    CubModule { layer: "block", name: "block_histogram" },
    CubModule { layer: "block", name: "block_load" },
    CubModule { layer: "block", name: "block_load_to_shared" },
    CubModule { layer: "block", name: "block_merge_sort" },
    CubModule { layer: "block", name: "block_radix_rank" },
    CubModule { layer: "block", name: "block_radix_sort" },
    CubModule { layer: "block", name: "block_raking_layout" },
    CubModule { layer: "block", name: "block_reduce" },
    CubModule { layer: "block", name: "block_run_length_decode" },
    CubModule { layer: "block", name: "block_scan" },
    CubModule { layer: "block", name: "block_shuffle" },
    CubModule { layer: "block", name: "block_store" },
    CubModule { layer: "block", name: "block_topk" },
    CubModule { layer: "block", name: "radix_rank_sort_operations" },
    CubModule { layer: "device", name: "device_adjacent_difference" },
    CubModule { layer: "device", name: "device_batched_topk" },
    CubModule { layer: "device", name: "device_copy" },
    CubModule { layer: "device", name: "device_find" },
    CubModule { layer: "device", name: "device_for" },
    CubModule { layer: "device", name: "device_histogram" },
    CubModule { layer: "device", name: "device_memcpy" },
    CubModule { layer: "device", name: "device_merge" },
    CubModule { layer: "device", name: "device_merge_sort" },
    CubModule { layer: "device", name: "device_partition" },
    CubModule { layer: "device", name: "device_radix_sort" },
    CubModule { layer: "device", name: "device_reduce" },
    CubModule { layer: "device", name: "device_run_length_encode" },
    CubModule { layer: "device", name: "device_scan" },
    CubModule { layer: "device", name: "device_segmented_radix_sort" },
    CubModule { layer: "device", name: "device_segmented_reduce" },
    CubModule { layer: "device", name: "device_segmented_scan" },
    CubModule { layer: "device", name: "device_segmented_sort" },
    CubModule { layer: "device", name: "device_select" },
    CubModule { layer: "device", name: "device_topk" },
    CubModule { layer: "device", name: "device_transform" },
    CubModule { layer: "grid", name: "grid_even_share" },
    CubModule { layer: "grid", name: "grid_mapping" },
    CubModule { layer: "grid", name: "grid_queue" },
    CubModule { layer: "iterator", name: "arg_index_input_iterator" },
    CubModule { layer: "iterator", name: "cache_modified_input_iterator" },
    CubModule { layer: "iterator", name: "cache_modified_output_iterator" },
    CubModule { layer: "iterator", name: "tex_obj_input_iterator" },
    CubModule { layer: "thread", name: "thread_load" },
    CubModule { layer: "thread", name: "thread_operators" },
    CubModule { layer: "thread", name: "thread_reduce" },
    CubModule { layer: "thread", name: "thread_scan" },
    CubModule { layer: "thread", name: "thread_search" },
    CubModule { layer: "thread", name: "thread_simd" },
    CubModule { layer: "thread", name: "thread_sort" },
    CubModule { layer: "thread", name: "thread_store" },
    CubModule { layer: "warp", name: "warp_exchange" },
    CubModule { layer: "warp", name: "warp_load" },
    CubModule { layer: "warp", name: "warp_merge_sort" },
    CubModule { layer: "warp", name: "warp_reduce" },
    CubModule { layer: "warp", name: "warp_reduce_batched" },
    CubModule { layer: "warp", name: "warp_scan" },
    CubModule { layer: "warp", name: "warp_store" },
    CubModule { layer: "warp", name: "warp_utils" },
];

pub fn cub_module_count() -> usize { CUB_MODULES.len() }

pub fn cub_layers() -> alloc::vec::Vec<&'static str> {
    use alloc::vec::Vec;
    let mut v = Vec::new();
    for m in CUB_MODULES {
        if !v.iter().any(|x| *x == m.layer) { v.push(m.layer); }
    }
    v
}
