//! AUTO-GENERATED by scripts/reverse-engineer-cccl.py — CCCL Thrust public headers.
//! CCCL version pin: 3.5.0

#![allow(dead_code)]

pub const CCCL_VERSION: &str = "3.5.0";

/// Public Thrust algorithm / facility header stems (thrust/*.h).
pub const THRUST_PUBLIC_HEADERS: &[&str] = &[
    "addressof",
    "adjacent_difference",
    "advance",
    "allocate_unique",
    "binary_search",
    "complex",
    "copy",
    "count",
    "device_allocator",
    "device_delete",
    "device_free",
    "device_make_unique",
    "device_malloc",
    "device_malloc_allocator",
    "device_new",
    "device_new_allocator",
    "device_ptr",
    "device_reference",
    "device_vector",
    "distance",
    "equal",
    "execution_policy",
    "extrema",
    "fill",
    "find",
    "for_each",
    "functional",
    "gather",
    "generate",
    "host_vector",
    "inner_product",
    "logical",
    "memory",
    "merge",
    "mismatch",
    "pair",
    "partition",
    "per_device_resource",
    "random",
    "reduce",
    "remove",
    "replace",
    "reverse",
    "scan",
    "scatter",
    "sequence",
    "set_operations",
    "shuffle",
    "sort",
    "swap",
    "system_error",
    "tabulate",
    "transform",
    "transform_reduce",
    "transform_scan",
    "tuple",
    "uninitialized_copy",
    "uninitialized_fill",
    "unique",
    "universal_allocator",
    "universal_ptr",
    "universal_vector",
    "version",
    "zip_function",
];

/// Host-side algorithms Hermes implements today (subset grows over time).
pub const HERMES_HOST_IMPLEMENTED: &[&str] = &[
    "copy",
    "fill",
    "count",
    "for_each",
    "transform",
    "reduce",
    "sequence",
    "equal",
    "find",
    "replace",
    "sort",
    "unique",
    "scan",
];

pub fn thrust_header_count() -> usize { THRUST_PUBLIC_HEADERS.len() }

pub fn is_public_thrust_header(stem: &str) -> bool {
    THRUST_PUBLIC_HEADERS.contains(&stem)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn thrust_table_has_core_algorithms() {
        assert!(is_public_thrust_header("copy"));
        assert!(is_public_thrust_header("sort"));
        assert!(is_public_thrust_header("reduce"));
        assert!(thrust_header_count() > 20);
    }
}
